# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c8cb0b2d13a03db4c54207c2e547a1a1da6a070ddaf219f58d374aa37c639a8e8b63f80abf9065305bf59e3aa300c7c2532f22882c2c8a071f27e7a7e6f0676

test:
  secret_key_base: e2c70fd33b914af7e9e9f5172e19a1cb253165fc64cafbae55023edc9c548c407e2d759eac7601a065d49de4c23d84c31bf630ae476416ca2e0d9076f3451687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
