# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



post1 = Post.create(author: "Jaden Cockrin", title: "The first Post", views: 55, content: "Hi Everyone!  This is the first post in this forum.  I'm just going to go over a few ground rules.  We want to keep this place as an open and free space to talk about anything, and just see where that leads.  So here's how this will work. \n First of all, anyone can post anything.  You just have to press the 'Join the Forum' button up at the top.  You don't need to sign up or even give your name.  Just post what you are thinking.  \n  Next, you can comment on anything.  Now, even though you can post anonymously, we do ask that you give a name for the comments, just so it is easier to hold a conversation.  It might be a confusing talk if everyone is referring to everyone else as 'Anonymous'. It doesn't need to be your real name.  Just a reference so we know who is talking to who.  \n Next, you CAN edit any post you want.  This might seem odd, but we thing that sometimes the best way to make an arguemnt is to clearly spell it out in the text.  This also encourages you to keep up and monitor discussions you have started. \n  Lastly, posts can be deleted.  At least five people need to vote to delete a post, but it can be done. \n And that is it.  Good luck, try to stay civil, and happy discussing! \n - Jaden")
comments1 = post1.comments.build([{name: "Ross", content: "I think this is a really good idea!"}, {name: "Rachel", content: "Me too!"}])

post = Post.create(title: "Lorem Ipsum", views: 0, content: "Bacon ipsum dolor amet beef ribs chicken spare ribs, landjaeger ham drumstick shoulder tenderloin cow ground round pork belly filet mignon kielbasa short loin pork chop. Cow filet mignon shoulder swine rump. Venison boudin alcatra short loin pork biltong. Pastrami salami turducken shank, strip steak shankle tail pig venison leberkas prosciutto meatloaf ham flank doner. Fatback chuck biltong kevin leberkas. Beef frankfurter ball tip jerky ground round shankle. \n Tail pancetta tenderloin shank swine flank pork chop turkey jowl spare ribs short loin. Beef ribs drumstick kielbasa pork prosciutto, andouille chicken. Pork loin ground round chicken jowl rump hamburger. Spare ribs drumstick pig beef pork loin flank salami pancetta sausage short ribs. Pancetta doner tongue alcatra. \n Bresaola porchetta jowl shank tenderloin, short loin drumstick beef pastrami. Sirloin pork loin venison, kevin biltong boudin pork belly ham filet mignon bresaola meatloaf pig chuck ball tip. Frankfurter tri-tip t-bone capicola leberkas chuck pastrami pork chop short loin shankle picanha salami. Tenderloin fatback jowl rump frankfurter pancetta bresaola meatloaf porchetta tail pork loin. \n Bresaola porchetta jowl shank tenderloin, short loin drumstick beef pastrami. Sirloin pork loin venison, kevin biltong boudin pork belly ham filet mignon bresaola meatloaf pig chuck ball tip. Frankfurter tri-tip t-bone capicola leberkas chuck pastrami pork chop short loin shankle picanha salami. Tenderloin fatback jowl rump frankfurter pancetta bresaola meatloaf porchetta tail pork loin.")

post2 = Post.create(author: "Cynthia Mudale", title: "The Importance of Outsiders", views: 22, content: "Hello everyone.  My name is Rachel and I am a hiring manager at a software development company.  I wanted to share my experiences with hiring.  Specifically, I wanted to share how I've noticed how hiring people who have experience outside of what might be considered 'traditional work' in a certain field usually leads to a better workspace. \n  The higih and low of it is this: people who are outsiders bring a great fresh perspective into the mix.  I see this all the time.  People from the tradition background of formal schooling and education usually know their stuff really well.  I mean REALLY WELL.  But sometimes there are projects and problems that get them hung up.  That's where the people from the non-traditional backgorunds usually shine.  They have a way of thinking in a manner that is 'outside the box' for any given industry.  \n  Plus, it shows real initiative when they didn't go down those traiditional or formal avenues, and still ended up with similar skills and knowledge.  In software, I usually look at the resumes of those that don't have CS degrees before the ones that do.  That's because the ones that didn't go to college, but instead sought out that knowledge on their own, usually demonstrate a greater passion for the work.  \n  So what do you all think?  Let me know.")
comments2 = post2.comments.build([{name: "Richard", content: "I used to run a product development team and I ablsolutely agree!"}, {name: "Dallas", content: "I'd like to see a formal study done on this sort of thing."}, {name: "Kylee", content: "Interesting..."}])

post3 = Post.create(author: "Joshy B.", title: "The Importance of Being Ernest", views: 11, content: "Okay, so I just read this and I'm still not sure I get it.  I will admit I wasn't really paying attention at the beginning because I didn't really want to read this play.  I'm in high school and it was for English class.  But it hooked me around teh time the cucumber sandwiches came into play. \n Anyway, can someone please explain to me what exacly the deal was with the ending.  And the title.  Like, is it a pun on his name or what?")

post4 = Post.create(author: "Winston Wells", title: "Great Time Management Techniques", views: 15, content: "I have been trying to find the best way to create more free time in my day.  Naturally, I have been looking at a lot of time management gurus, or poeple who claim to be as such.  Anyway, here are some things I thought I might bring to your attention. \n  First of all, divide your time into 20 minute incrments.  That is is the only piece of advice I have heard that consistently works.  Work for 20 minutes.  Rest for 5.  Do that three times, and then, after the third time, rest for 25 minutes.  Just do that through the day.  It might sound weird, but it does help you concentrate more and get through work faster. \n Are there any time management techniques you have heard of lately?")
comment3 = post4.comments.create(name: "Wallas", content: "This technique worked GREAT for me!  Thanks!!!")

post5 = Post.create(title: "This is It", views: 16, content: "So, this is kind of a weird thing.  I;m pretty proud of something I've done lately, but I don't know if I should share it with anyone.  Like I don't know if anyone will be as excited about it as I am.  So this is what I'm going to do. \n Comment on this if you want to hear about it.  I won't tell you much up front.  All I will say is that it is definitely an unorthadox little thing I did.  So let me know if that sells you on it.")
comments5 = post5.comments.build([{name: "Jake", content: "I want to know"}, {name: "Rosy", content: "I want to know"}, {name: "Rick", content: "I want to know"}, {name: "Morty", content: "I want to know"}, {name: "Summer", content: "I want to know"}, {name: "Beth", content: "I want to know"}])
