# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
post1 = Post.create(title: "BREAKING: Intern candidate working on Ruby on Rails blog.", content: "&emsp;&emsp;&nbsp;&nbsp;Reports are flooding into the office this morning, babbling about an intern candidate who is working on a Ruby on Rails blog. Cam Pleet-Laer, one of our senior reporters, has it on good authority that the blog will feature a beautifully stylized user interface that is the result of over a decade of A/B testing. Other reports state that the blog will have the latest news, often fabricated by the blog’s owner. Some rumors have stated that the blog will simply contain Chuck Norris jokes and the daily Garfield strip, but these are highly unlikely, due to the prestigious nature of the project. An anonymous source close to the project says that the first venture will be an investigative piece on the recent CIA files released by WikiLeaks, in collaboration with VICE. VICE has yet to respond to our inquiries, but that is of no surprise, considering the sensitive subject matter. This same source has stated that they are expecting an early April release date, which we will all be eagerly awaiting. Stay tuned for further updates.", imageSrc:"http://atulhost.com/wp-content/uploads/2016/02/ruby-on-rails.jpg")
post2 = Post.create(title: "The Best of Chuck", content: "• While other children were playing in sand, Chuck was playing in concrete.\n<br>• Bill Gates lives in constant fear that Chuck Norris' PC will crash.\n<br>• If it looks like chicken, tastes like chicken, and feels like chicken but Chuck Norris says its beef, then it's beef.\n<br>• Chuck Norris can finish an entire bottle of milk in 5 seconds. Using a fork.\n<br>• Chuck Norris makes fire by rubbing 2 ice cubes together.\n<br>• Chuck Norris has a diary. It's called the Guinness Book of World Records.\n<br>• When Chuck Norris was born he drove his mom home from the hospital.\n<br>• There once was a street called Chuck Norris, but the name was changed for public safety because nobody crosses Chuck Norris and lives.\n<br>• Big foot claims he saw Chuck Norris.\n<br>• Chuck Norris can drift on a horse.\n<br>• Chuck Norris beat the sun in a staring contest.\n<br>• Giraffes were created when Chuck Norris uppercutted a horse.\n<br>• Chuck Norris once went to Mars. That’s why there are no signs of life.\n<br>• Chuck Norris is the reason Waldo is hiding.\n<br>• Jack was nimble, Jack was quick, but Jack still couldn't dodge Chuck Norris' roundhouse kick.\n<br>• Chuck Norris' calendar goes straight from March 31st to April 2nd. No one fools Chuck Norris.\n<br>• Chuck Norris's Blood Type is AK-47.\n<br>• Chuck Norris plays Russian Roulette with a fully loaded revolver... and wins.\n<br>• Chuck Norris' dog is trained to pick up his own poop because Chuck Norris will not take shit from anyone.\n<br>• Chuck Norris doesn’t wear a watch. He decides what time it is.\n<br>• Chuck Norris can drown a fish.\n<br>• The only time Chuck Norris was wrong was when he thought he had made a mistake.\n", imageSrc: "")
post3 = Post.create(title: "Fake-News Free! – Vlad’s Blog rated 100% reliable by trusted sources", content: "&emsp;&emsp;&nbsp;&nbsp;A decade-long research project undertaken by 4 dedicated teams of Stanford PhDs (pictured above) has concluded that Vlad’s Blog is a 100% credible and trusted news source. This report comes at a critical point in time, where every news source on Earth has been plagued by the indefensible fake-news epidemic. Statistics released just this AM have shown a 1,000% increase in page visits to Vlad’s Blog, and new statistics predict that number hitting at least 1,000,000% by the end of the day. That figure is expected to plateau at around 4,734,607.42% this time next year.", imageSrc: "https://c1.staticflickr.com/5/4113/4988365370_e23f9a2ca9_b.jpg")
post4 = Post.create(title: "Hedgeye CEO Keith McCullough Resigns Suddenly, Intern candidate named Interim Director", content: "&emsp;&emsp;&nbsp;&nbsp;A surprising turn of events unfolded this Sunday morning; it was announced that Keith McCullough, CEO of Hedgeye, has abruptly resigned, stating concerns over “future company direction” as his main motivator. An even more shocking blow fell hours later as reports of the Interim Director were released. It appears that a person known simply as, “Vlad”, has stepped in as Hedgeye’s Interim Director. Reports have stated that Vlad was previously being considered for an intern position, but due to some “glitch” in the system, has been promoted to the head of the company. HR, IT, and the NSA are all currently looking into the matter.\n<br>\n<b>UPDATE:</b> The exhaustive, 2 hour-long search has been called off by the Interim Director due to lack of results. Hedgeye has issued a public statement declaring that they do not believe any foul-play was involved. ", imageSrc: "http://i.imgur.com/Qjc5MOW.jpg")